-- 0006_create_gold_sales_c086_star.sql
-- Build the gold Kimball star over silver.sales_c086 (the 0005 build).
--
-- SUPERSEDES 0002_create_gold_star.sql. Authoritative gold build for the FINAL map.
-- Differs from 0002 by design:
--   * fct_sales PK = Sale_SK (carried from silver); natural key is degenerate-on-fact.
--   * 2 measures only: Gross_Sales + Quantity (net/tax/discount dropped).
--   * NEW dim_product_purchaser (the counter agent, 16 members).
--   * dim_customer keyed on Customer_ID_Clean (the 'WALK_IN' remap), not raw customer.
--   * No business_segment (none analyst-supplied).
--   * PascalCase quoted identifiers.
--
-- 6 ENTITY dims each carry an unknown member at _sk = -1 (fact FKs COALESCE to -1).
-- dim_date carries NO -1 member (marked date table, rule S8): an unmatched fact date
-- is rejected by Date_SK NOT NULL, never absorbed by a sentinel.
-- Idempotent: drop fact before dims (FK order), recreate all in one transaction.
-- Save UTF-8 without BOM (English labels only here).

SET client_encoding TO 'UTF8';

BEGIN;

CREATE SCHEMA IF NOT EXISTS gold;

-- FK dependency order: fact first.
DROP TABLE IF EXISTS gold.fct_sales;
DROP TABLE IF EXISTS gold.dim_product;
DROP TABLE IF EXISTS gold.dim_customer;
DROP TABLE IF EXISTS gold.dim_salesperson;
DROP TABLE IF EXISTS gold.dim_product_purchaser;
DROP TABLE IF EXISTS gold.dim_billing_type;
DROP TABLE IF EXISTS gold.dim_branch;
DROP TABLE IF EXISTS gold.dim_date;

-- ============================================================ dim_product
CREATE TABLE gold.dim_product (
  "Product_SK"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Product_ID"   TEXT,                 -- natural key
  "Product_Name" TEXT,
  "Brand"        TEXT,
  "Category"     TEXT,
  "Subcategory"  TEXT,
  "Segment"      TEXT,
  "Division"     TEXT,
  "Cluster"      TEXT
);
INSERT INTO gold.dim_product OVERRIDING SYSTEM VALUE
  VALUES (-1,'UNKNOWN','Unknown','Unknown','Unknown','Unknown','Unknown','Unknown','Unknown');
-- Product_ID -> attributes verified 1:1 (material<->material_desc 9,690<->9,690); max() safe.
INSERT INTO gold.dim_product
  ("Product_ID","Product_Name","Brand","Category","Subcategory","Segment","Division","Cluster")
SELECT "Product_ID", max("Product_Name"), max("Brand"), max("Category"),
       max("Subcategory"), max("Segment"), max("Division"), max("Cluster")
FROM silver.sales_c086
GROUP BY "Product_ID";

-- ============================================================ dim_customer (keyed on the clean id)
CREATE TABLE gold.dim_customer (
  "Customer_SK"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Customer_ID"   TEXT,               -- the cleaned id (Customer_ID_Clean; 'WALK_IN' for site-code rows)
  "Customer_Name" TEXT
);
INSERT INTO gold.dim_customer OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown');
-- keyed on Customer_ID_Clean: the 85,911 walk-in rows collapse to one 'WALK_IN' member,
-- NOT a member literally named 'C086' (the site code).
INSERT INTO gold.dim_customer ("Customer_ID","Customer_Name")
SELECT "Customer_ID_Clean", max("Customer_Name")
FROM silver.sales_c086
WHERE "Customer_ID_Clean" IS NOT NULL
GROUP BY "Customer_ID_Clean";

-- ============================================================ dim_salesperson
CREATE TABLE gold.dim_salesperson (
  "Salesperson_SK"       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Salesperson_ID"       TEXT,
  "Salesperson_Name"     TEXT,
  "Salesperson_Position" TEXT
);
INSERT INTO gold.dim_salesperson OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown','Unknown');
-- blank Salesperson_ID rows (NULL, ~1,748) fold into the -1 member (excluded here).
INSERT INTO gold.dim_salesperson ("Salesperson_ID","Salesperson_Name","Salesperson_Position")
SELECT "Salesperson_ID", max("Salesperson_Name"), max("Salesperson_Position")
FROM silver.sales_c086
WHERE "Salesperson_ID" IS NOT NULL
GROUP BY "Salesperson_ID";

-- ============================================================ dim_product_purchaser (NEW -- counter agent)
CREATE TABLE gold.dim_product_purchaser (
  "Purchaser_SK"      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Product_Purchaser" TEXT
);
INSERT INTO gold.dim_product_purchaser OVERRIDING SYSTEM VALUE VALUES (-1,'Unknown');
INSERT INTO gold.dim_product_purchaser ("Product_Purchaser")
SELECT "Product_Purchaser"
FROM silver.sales_c086
WHERE "Product_Purchaser" IS NOT NULL
GROUP BY "Product_Purchaser";

-- ============================================================ dim_billing_type
CREATE TABLE gold.dim_billing_type (
  "Billing_Type_SK"    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Billing_Type_Code"  TEXT,
  "Billing_Type_Label" TEXT,
  "Is_Return"          BOOLEAN
);
INSERT INTO gold.dim_billing_type OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown',FALSE);
INSERT INTO gold.dim_billing_type ("Billing_Type_Code","Billing_Type_Label","Is_Return")
SELECT "Billing_Type_Code", max("Billing_Type_Label"), bool_or("Is_Return")
FROM silver.sales_c086 GROUP BY "Billing_Type_Code";

-- ============================================================ dim_branch
CREATE TABLE gold.dim_branch (
  "Branch_SK"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Branch_ID"   TEXT,
  "Branch_Name" TEXT
);
INSERT INTO gold.dim_branch OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown');
INSERT INTO gold.dim_branch ("Branch_ID","Branch_Name")
SELECT "Branch_ID", max("Branch_Name") FROM silver.sales_c086 GROUP BY "Branch_ID";

-- ============================================================ dim_date (contiguous; NO -1 member)
CREATE TABLE gold.dim_date (
  "Date_SK"    INT PRIMARY KEY,             -- smart key YYYYMMDD
  "Full_Date"  DATE,
  "Year"       SMALLINT,
  "Quarter"    SMALLINT,
  "Month"      SMALLINT,
  "Month_Name" TEXT,
  "Day"        SMALLINT,
  "Day_Name"   TEXT,
  "ISO_Week"   SMALLINT,
  "Is_Weekend" BOOLEAN
);
-- NO -1 unknown member: dim_date is a MARKED date table (Power BI validates it as
-- unique/contiguous/no-nulls). A -1/NULL member would break marking it (rule S8 / D10).
-- An unmatched fact date is handled by Date_SK NOT NULL on the fact (fail loud).
INSERT INTO gold.dim_date
SELECT
  (to_char(d,'YYYYMMDD'))::int       AS "Date_SK",
  d::date                            AS "Full_Date",
  extract(year FROM d)::smallint,
  extract(quarter FROM d)::smallint,
  extract(month FROM d)::smallint,
  to_char(d,'Month'),
  extract(day FROM d)::smallint,
  to_char(d,'Day'),
  extract(week FROM d)::smallint,
  (extract(isodow FROM d) >= 6)      AS "Is_Weekend"
FROM generate_series(DATE '2023-01-01', DATE '2025-12-31', INTERVAL '1 day') AS g(d);

-- ============================================================ fct_sales
CREATE TABLE gold.fct_sales (
  "Sale_SK"           BIGINT PRIMARY KEY,        -- surrogate PK, carried from silver
  -- degenerate dimensions (live on the fact)
  "Invoice"           TEXT,                      -- per-invoice reference (reference_no)
  -- foreign keys to dims
  "Product_SK"        INT NOT NULL,
  "Customer_SK"       INT NOT NULL,
  "Salesperson_SK"    INT NOT NULL,
  "Purchaser_SK"      INT NOT NULL,
  "Date_SK"           INT NOT NULL,
  "Billing_Type_SK"   INT NOT NULL,
  "Branch_SK"         INT NOT NULL,
  -- measures (2)
  "Gross_Sales"       NUMERIC(18,2),
  "Quantity"          NUMERIC(18,3),
  "Is_Return"         BOOLEAN
);
INSERT INTO gold.fct_sales
  ("Sale_SK","Invoice",
   "Product_SK","Customer_SK","Salesperson_SK","Purchaser_SK","Date_SK","Billing_Type_SK","Branch_SK",
   "Gross_Sales","Quantity","Is_Return")
SELECT
  s."Sale_SK", s."Invoice",
  COALESCE(dp."Product_SK", -1),
  COALESCE(dc."Customer_SK", -1),
  COALESCE(dsp."Salesperson_SK", -1),
  COALESCE(dpp."Purchaser_SK", -1),
  dd."Date_SK",   -- NO COALESCE to -1: an unmatched/NULL fact date yields NULL and is
                  -- rejected by Date_SK NOT NULL (fail loud -- a calendar-coverage bug).
  COALESCE(dbt."Billing_Type_SK", -1),
  COALESCE(db."Branch_SK", -1),
  s."Gross_Sales", s."Quantity", s."Is_Return"
FROM silver.sales_c086 s
LEFT JOIN gold.dim_product           dp  ON dp."Product_ID"        = s."Product_ID"
LEFT JOIN gold.dim_customer          dc  ON dc."Customer_ID"       = s."Customer_ID_Clean"
LEFT JOIN gold.dim_salesperson       dsp ON dsp."Salesperson_ID"   = s."Salesperson_ID"
LEFT JOIN gold.dim_product_purchaser dpp ON dpp."Product_Purchaser" = s."Product_Purchaser"
LEFT JOIN gold.dim_date              dd  ON dd."Full_Date"         = s."Sale_Date"
LEFT JOIN gold.dim_billing_type      dbt ON dbt."Billing_Type_Code" = s."Billing_Type_Code"
LEFT JOIN gold.dim_branch            db  ON db."Branch_ID"         = s."Branch_ID";

-- FK constraints (after load, so the -1 members and rows exist first)
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_product      FOREIGN KEY ("Product_SK")      REFERENCES gold.dim_product ("Product_SK");
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_customer     FOREIGN KEY ("Customer_SK")     REFERENCES gold.dim_customer ("Customer_SK");
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_salesperson  FOREIGN KEY ("Salesperson_SK")  REFERENCES gold.dim_salesperson ("Salesperson_SK");
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_purchaser    FOREIGN KEY ("Purchaser_SK")    REFERENCES gold.dim_product_purchaser ("Purchaser_SK");
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_date         FOREIGN KEY ("Date_SK")         REFERENCES gold.dim_date ("Date_SK");
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_billing_type FOREIGN KEY ("Billing_Type_SK") REFERENCES gold.dim_billing_type ("Billing_Type_SK");
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_branch       FOREIGN KEY ("Branch_SK")       REFERENCES gold.dim_branch ("Branch_SK");

-- indexes on FKs for star-join performance
CREATE INDEX idx_fct_product_sk      ON gold.fct_sales ("Product_SK");
CREATE INDEX idx_fct_customer_sk     ON gold.fct_sales ("Customer_SK");
CREATE INDEX idx_fct_salesperson_sk  ON gold.fct_sales ("Salesperson_SK");
CREATE INDEX idx_fct_purchaser_sk    ON gold.fct_sales ("Purchaser_SK");
CREATE INDEX idx_fct_date_sk         ON gold.fct_sales ("Date_SK");
CREATE INDEX idx_fct_billing_type_sk ON gold.fct_sales ("Billing_Type_SK");
CREATE INDEX idx_fct_branch_sk       ON gold.fct_sales ("Branch_SK");

COMMIT;
