-- 0008_create_gold_finance_gl_star.sql
-- Build the gold Kimball star(s) over silver.finance_gl_actuals and
-- silver.finance_gl_budget -- spec 137's finance GL genericity proof.
--
-- AUTHORING ONLY. Never executed by this feature -- no database connection is
-- opened anywhere in spec 137 (every live leg reads [PENDING LIVE PROFILE]).
-- Authored because BOTH finance tables' mapping gates are CLEARED
-- (mappings/finance_gl_actuals/readiness-status.yaml and
-- mappings/finance_gl_budget/readiness-status.yaml approvals[]).
--
-- TWO FACTS, NEVER MERGED (spec SC-004, FR-009):
--   gold.fct_gl_actuals_fgl  -- grain: one journal line within one journal entry
--   gold.fct_gl_budget_fgl   -- grain: one amount per account x dept x fiscal
--                                quarter x budget_version
-- sharing CONFORMED dimensions gold.dim_account_fgl and gold.dim_department_fgl
-- (ruled `conformed` by Ahmed Shaaban, 2026-07-30 -- docs/quality/
-- conformed-dimension-map.yaml; HR1 verified matching surrogate_key + shared
-- attribute types across both stars, FR-005). Declared IDENTICALLY in both
-- mappings/finance_gl_actuals/source-map.yaml and mappings/finance_gl_budget/
-- source-map.yaml -- see ledger row L1 (no in-repo mechanism yet detects the two
-- declarations drifting; that is a documentation/tooling finding, not a blocker).
--
-- gold.dim_cost_center_fgl is ACTUALS-ONLY (the budget source has no cost-center
-- concept; the two facts meet at DEPARTMENT level, per sub-decision C2).
-- gold.dim_date_fgl (daily, RC15 contiguous) is ACTUALS-ONLY.
-- gold.dim_fiscal_period_fgl (quarter grain, sourced from fiscal_calendar) is
-- BUDGET-ONLY -- the RC15 daily calendar is a closed Gregorian contract that cannot
-- carry a fiscal period (ledger row L5), so budget keys on its own period dimension
-- instead of the daily calendar.
--
-- FR-010: actuals MAY be aggregated UP to the budget's comparison grain (quarter x
-- account x department) in downstream DAX/SQL; nothing in this migration
-- disaggregates budget_amount DOWN to a finer grain. No statement below spreads,
-- allocates, divides, or otherwise disaggregates budget_amount (verified in T024a).
-- FR-011: budget_version is part of fct_gl_budget_fgl's key; no statement below
-- updates, deletes, or overwrites a prior version's rows (verified in T024b).
--
-- CLEARING ACCOUNTS (sub-decision C1, Option A): kept through gold on
-- dim_account_fgl.account_type = 'CLEARING' so the double-entry balance stays
-- provable in the warehouse; excluded from P&L reporting by a metric-contract-level
-- filter (dim_account_fgl.account_type <> 'CLEARING'), NOT dropped here.
--
-- Idempotent: drop facts before dims (FK order), recreate all in one transaction.
-- ASCII only (English labels); UTF-8 no BOM.

SET client_encoding TO 'UTF8';

BEGIN;

CREATE SCHEMA IF NOT EXISTS gold;

-- FK dependency order: facts first, then dims.
DROP TABLE IF EXISTS gold.fct_gl_actuals_fgl;
DROP TABLE IF EXISTS gold.fct_gl_budget_fgl;
DROP TABLE IF EXISTS gold.dim_cost_center_fgl;
DROP TABLE IF EXISTS gold.dim_fiscal_period_fgl;
DROP TABLE IF EXISTS gold.dim_account_fgl;
DROP TABLE IF EXISTS gold.dim_department_fgl;
DROP TABLE IF EXISTS gold.dim_date_fgl;

-- ============================================================ dim_account_fgl
-- CONFORMED across fct_gl_actuals_fgl and fct_gl_budget_fgl.
CREATE TABLE gold.dim_account_fgl (
  account_sk          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code        TEXT,                 -- natural key
  account_name        TEXT,
  account_type        TEXT,                 -- REVENUE | COGS | OPEX | CLEARING
  parent_account_code TEXT                  -- flat denorm hierarchy level (RC12)
);
INSERT INTO gold.dim_account_fgl OVERRIDING SYSTEM VALUE
  VALUES (-1, 'UNKNOWN', 'Unknown', 'UNKNOWN', NULL);
INSERT INTO gold.dim_account_fgl (account_code, account_name, account_type, parent_account_code)
SELECT account_code, account_name, account_type, parent_account_code
FROM bronze.accounts
GROUP BY account_code, account_name, account_type, parent_account_code;

-- ============================================================ dim_department_fgl
-- CONFORMED across fct_gl_actuals_fgl and fct_gl_budget_fgl. Department-level only
-- (the cost-center child list lives in dim_cost_center_fgl, actuals-only).
CREATE TABLE gold.dim_department_fgl (
  department_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_code TEXT,                     -- natural key
  department_name TEXT
);
INSERT INTO gold.dim_department_fgl OVERRIDING SYSTEM VALUE VALUES (-1, 'UNKNOWN', 'Unknown');
INSERT INTO gold.dim_department_fgl (department_code, department_name)
SELECT department_code, department_name
FROM bronze.departments
GROUP BY department_code, department_name;

-- ============================================================ dim_cost_center_fgl
-- ACTUALS-ONLY: the budget source has no cost-center concept. department_code is
-- a flat denorm rollup (RC12) to the conformed department level, not a snowflake FK.
CREATE TABLE gold.dim_cost_center_fgl (
  cost_center_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cost_center_code TEXT,                    -- natural key
  cost_center_name TEXT,
  department_code  TEXT                     -- flat denorm rollup (RC12)
);
INSERT INTO gold.dim_cost_center_fgl OVERRIDING SYSTEM VALUE
  VALUES (-1, 'UNKNOWN', 'Unknown', NULL);
INSERT INTO gold.dim_cost_center_fgl (cost_center_code, cost_center_name, department_code)
SELECT cost_center_code, cost_center_name, department_code
FROM bronze.departments
GROUP BY cost_center_code, cost_center_name, department_code;

-- ============================================================ dim_date_fgl (contiguous)
-- ACTUALS-ONLY. RC15 daily calendar; a marked date table carries NO -1 member
-- (rule S8) -- an unmatched fact date is rejected by date_sk NOT NULL, never
-- absorbed by a sentinel. Span from the approved source-map.yaml
-- (mappings/finance_gl_actuals/source-map.yaml gold_star.date_dimension.span):
-- earliest/latest posting_date in the clean synthetic source.
CREATE TABLE gold.dim_date_fgl (
  date_sk    INT PRIMARY KEY,                -- smart key YYYYMMDD
  full_date  DATE,
  year       SMALLINT,
  quarter    SMALLINT,
  month      SMALLINT,
  month_name TEXT,
  day        SMALLINT,
  day_name   TEXT,
  iso_week   SMALLINT,
  is_weekend BOOLEAN
);
INSERT INTO gold.dim_date_fgl
SELECT
  (to_char(d,'YYYYMMDD'))::int       AS date_sk,
  d::date                             AS full_date,
  extract(year FROM d)::smallint,
  extract(quarter FROM d)::smallint,
  extract(month FROM d)::smallint,
  to_char(d,'Month'),
  extract(day FROM d)::smallint,
  to_char(d,'Day'),
  extract(week FROM d)::smallint,
  (extract(isodow FROM d) >= 6)       AS is_weekend
FROM generate_series(DATE '2024-01-01', DATE '2025-12-31', INTERVAL '1 day') AS g(d);

-- ============================================================ dim_fiscal_period_fgl
-- BUDGET-ONLY. Quarter-grain period dimension sourced from bronze.fiscal_calendar --
-- NOT the daily RC15 calendar, which is a closed Gregorian contract that cannot
-- carry a fiscal period (ledger row L5). Smart key YYYYQ (e.g. 20241).
CREATE TABLE gold.dim_fiscal_period_fgl (
  fiscal_period_sk  INT PRIMARY KEY,
  fiscal_year       SMALLINT,
  fiscal_quarter    SMALLINT,
  period_start_date DATE,
  period_end_date   DATE
);
INSERT INTO gold.dim_fiscal_period_fgl VALUES (-1, NULL, NULL, NULL, NULL);
INSERT INTO gold.dim_fiscal_period_fgl (fiscal_period_sk, fiscal_year, fiscal_quarter, period_start_date, period_end_date)
SELECT
  (fiscal_year::int * 10 + fiscal_quarter::int) AS fiscal_period_sk,
  fiscal_year::smallint,
  fiscal_quarter::smallint,
  period_start_date::date,
  period_end_date::date
FROM bronze.fiscal_calendar;

-- ============================================================ fct_gl_actuals_fgl
-- Grain: one journal line within one journal entry (source-map.yaml meta.grain).
-- business_key = (journal_entry_id, line_id), matching the silver PK.
CREATE TABLE gold.fct_gl_actuals_fgl (
  fct_gl_actuals_fgl_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- degenerate dimensions (live on the fact; grain keys carry no attributes of
  -- their own, RC14)
  journal_entry_id      TEXT NOT NULL,
  line_id               SMALLINT NOT NULL,
  currency_code         TEXT,
  description           TEXT,
  -- foreign keys to dims
  account_sk            INT NOT NULL,
  department_sk         INT NOT NULL,
  cost_center_sk        INT NOT NULL,
  date_sk               INT NOT NULL,
  -- measures (RC9: independent landed measures)
  debit_amount          NUMERIC(18,2),
  credit_amount         NUMERIC(18,2),
  -- derived magnitude (OD-1 ruling: positive presentation; direction_of_good
  -- carries polarity at the contract layer, never the arithmetic sign here).
  -- Exactly one of debit/credit is non-zero per line, so their SUM is that side's
  -- magnitude with no sign arithmetic (mappings/finance_gl_actuals/source-map.yaml
  -- derived_columns.amount).
  amount                NUMERIC(18,2)
);
INSERT INTO gold.fct_gl_actuals_fgl
  (journal_entry_id, line_id, currency_code, description,
   account_sk, department_sk, cost_center_sk, date_sk,
   debit_amount, credit_amount, amount)
SELECT
  s.journal_entry_id, s.line_id, s.currency_code, s.description,
  COALESCE(da.account_sk, -1),
  COALESCE(dd.department_sk, -1),
  COALESCE(dc.cost_center_sk, -1),
  dt.date_sk,     -- NO COALESCE to a -1 date member: an unmatched/NULL fact date
                  -- yields NULL and is rejected by date_sk NOT NULL (fail loud,
                  -- mirrors gold.fct_sales_rss's dim_date_rss convention).
  s.debit_amount, s.credit_amount,
  (s.debit_amount + s.credit_amount) AS amount
FROM silver.finance_gl_actuals s
LEFT JOIN gold.dim_account_fgl      da ON da.account_code    = s.account_code
LEFT JOIN gold.dim_department_fgl   dd ON dd.department_code = s.department_code
LEFT JOIN gold.dim_cost_center_fgl  dc ON dc.cost_center_code = s.cost_center_code
LEFT JOIN gold.dim_date_fgl         dt ON dt.full_date        = s.posting_date;

-- Declared grain enforced physically (audit C36 -- a double-insert / partial re-run
-- would otherwise silently duplicate rows with no constraint failing).
ALTER TABLE gold.fct_gl_actuals_fgl
  ADD CONSTRAINT uq_fct_gl_actuals_fgl_grain UNIQUE (journal_entry_id, line_id);

ALTER TABLE gold.fct_gl_actuals_fgl ADD CONSTRAINT fk_fct_gl_actuals_account       FOREIGN KEY (account_sk)     REFERENCES gold.dim_account_fgl (account_sk);
ALTER TABLE gold.fct_gl_actuals_fgl ADD CONSTRAINT fk_fct_gl_actuals_department    FOREIGN KEY (department_sk)  REFERENCES gold.dim_department_fgl (department_sk);
ALTER TABLE gold.fct_gl_actuals_fgl ADD CONSTRAINT fk_fct_gl_actuals_cost_center   FOREIGN KEY (cost_center_sk) REFERENCES gold.dim_cost_center_fgl (cost_center_sk);
ALTER TABLE gold.fct_gl_actuals_fgl ADD CONSTRAINT fk_fct_gl_actuals_date          FOREIGN KEY (date_sk)        REFERENCES gold.dim_date_fgl (date_sk);

CREATE INDEX idx_fct_gl_actuals_account_sk    ON gold.fct_gl_actuals_fgl (account_sk);
CREATE INDEX idx_fct_gl_actuals_department_sk ON gold.fct_gl_actuals_fgl (department_sk);
CREATE INDEX idx_fct_gl_actuals_date_sk       ON gold.fct_gl_actuals_fgl (date_sk);

-- ============================================================ fct_gl_budget_fgl
-- Grain: one amount per account x department x fiscal quarter x budget_version
-- (source-map.yaml meta.grain) -- DISTINCT from the actuals grain; never merged.
-- budget_version is part of the declared business key (FR-011), carried as a
-- degenerate dimension so every query can -- and must -- pin its version.
CREATE TABLE gold.fct_gl_budget_fgl (
  fct_gl_budget_fgl_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- degenerate dimensions
  budget_version       TEXT NOT NULL,        -- PART OF IDENTITY, not an attribute
  currency_code         TEXT,
  -- foreign keys to dims (fiscal_period_fgl, NOT the daily date dim -- see L5)
  account_sk            INT NOT NULL,
  department_sk         INT NOT NULL,
  fiscal_period_sk      INT NOT NULL,
  -- measure: additive AT and ABOVE its own grain only; never disaggregated below
  -- quarter (OD-3). Nothing in this INSERT spreads, allocates, divides, or
  -- otherwise disaggregates budget_amount to a finer grain (FR-010, verified T024a).
  budget_amount         NUMERIC(18,2)
);
INSERT INTO gold.fct_gl_budget_fgl
  (budget_version, currency_code, account_sk, department_sk, fiscal_period_sk, budget_amount)
SELECT
  s.budget_version, s.currency_code,
  COALESCE(da.account_sk, -1),
  COALESCE(dd.department_sk, -1),
  COALESCE(dfp.fiscal_period_sk, -1),
  s.budget_amount
FROM silver.finance_gl_budget s
LEFT JOIN gold.dim_account_fgl        da  ON da.account_code    = s.account_code
LEFT JOIN gold.dim_department_fgl     dd  ON dd.department_code = s.department_code
LEFT JOIN gold.dim_fiscal_period_fgl  dfp ON dfp.fiscal_year    = s.fiscal_year
                                          AND dfp.fiscal_quarter = s.fiscal_quarter;

-- Declared grain enforced physically, WITH budget_version as part of the key
-- (FR-011: a new version ADDS rows; this constraint makes overwriting a prior
-- version's rows in place a primary-key violation, not a silent UPSERT).
ALTER TABLE gold.fct_gl_budget_fgl
  ADD CONSTRAINT uq_fct_gl_budget_fgl_grain
  UNIQUE (account_sk, department_sk, fiscal_period_sk, budget_version);

ALTER TABLE gold.fct_gl_budget_fgl ADD CONSTRAINT fk_fct_gl_budget_account        FOREIGN KEY (account_sk)       REFERENCES gold.dim_account_fgl (account_sk);
ALTER TABLE gold.fct_gl_budget_fgl ADD CONSTRAINT fk_fct_gl_budget_department     FOREIGN KEY (department_sk)    REFERENCES gold.dim_department_fgl (department_sk);
ALTER TABLE gold.fct_gl_budget_fgl ADD CONSTRAINT fk_fct_gl_budget_fiscal_period  FOREIGN KEY (fiscal_period_sk) REFERENCES gold.dim_fiscal_period_fgl (fiscal_period_sk);

CREATE INDEX idx_fct_gl_budget_account_sk        ON gold.fct_gl_budget_fgl (account_sk);
CREATE INDEX idx_fct_gl_budget_department_sk     ON gold.fct_gl_budget_fgl (department_sk);
CREATE INDEX idx_fct_gl_budget_fiscal_period_sk  ON gold.fct_gl_budget_fgl (fiscal_period_sk);
CREATE INDEX idx_fct_gl_budget_version            ON gold.fct_gl_budget_fgl (budget_version);

COMMIT;
