"""Generate the locally-owned pin manifest for the vendored Spec Kit extensions.

Issue #603. KF-2 pinned the five ``speckit-git-*`` skills -- the *projection* --
and left ``.specify/extensions/``, the *generator* that produces them, unpinned by
either upstream manifest. Drift in the thing that makes the verified artifact stayed
undetectable while the artifact itself verified: verification that looks complete and
is not. The unpinned surface is also the higher-risk one, because it holds executable
bash and PowerShell rather than skill prose.

**Why a third manifest instead of extending the other two.** Neither
``.specify/integrations/claude.manifest.json`` nor ``speckit.manifest.json`` has a
local writer -- both were produced by upstream's installer (``specify init``) in
`1eb0c98`, carrying its ``version`` and ``installed_at``. Appending entries by hand
would be drift that the next re-vendor silently discards. This manifest is authored
here, owned here, and regenerated by this script.

**Hashing convention: the git BLOB, not the working tree.** The two upstream manifests
were measured against real data before choosing this:

    claude.manifest.json    14/14 entries match sha256(blob)
    speckit.manifest.json   10/10 entries match sha256(blob)

A single rule reproduces all 24 existing pins. The apparent "two conventions" -- the
five ``.ps1`` entries verifying only after CRLF->LF normalization, the ``.md`` entries
verifying raw -- is a filesystem artifact, not a policy difference: ``.gitattributes``
gives the ``.md`` files ``eol=lf`` so their checkout bytes equal their blob bytes, while
``text=auto`` files are checked out CRLF on Windows and LF elsewhere.

That matters beyond tidiness. The extension surface spans three ``.gitattributes``
classes (``eol=lf``, ``eol=crlf``, and unspecified ``text=auto``), so a working-tree
hash of ``initialize-repo.ps1`` would differ between this Windows checkout and
``ubuntu-latest`` -- green locally and red in CI, or the reverse. Blob hashing is
platform-independent by construction.

Usage::

    python scripts/pin_speckit_extensions.py            # verify, exit 1 on drift
    python scripts/pin_speckit_extensions.py --write    # regenerate the manifest
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = Path(".specify/integrations/extensions.manifest.json")

#: Every tracked path under these roots is pinned. Directories are swept rather than
#: enumerated so that a file ADDED by a re-vendor cannot slip in unpinned -- the
#: failure mode a hand-written list invites. `templates-are-enumerated-not-globbed`
#: records the opposite lesson for packaging; the difference is that packaging must
#: not ship surprises, whereas provenance must not MISS them.
PINNED_ROOTS = (
    ".specify/extensions",
    ".specify/workflows",
)

#: Individually pinned files that do not live under a swept root.
PINNED_FILES = (
    ".specify/extensions.yml",
    ".specify/integration.json",
)


def _run_git(args: list[str], *, root: Path) -> bytes:
    result = subprocess.run(  # noqa: S603 -- fixed argv, no shell
        ["git", *args],
        cwd=root,
        check=True,
        capture_output=True,
    )
    return result.stdout


def blob_sha256(path: str, *, root: Path) -> str:
    """Hash the file's git blob -- what a checkout would produce anywhere.

    Reading the index (``:path``) rather than HEAD means a staged edit is measured,
    so regenerating and verifying agree during a re-vendor before it is committed.
    """
    return hashlib.sha256(
        _run_git(["cat-file", "blob", f":{path}"], root=root)
    ).hexdigest()


def pinned_paths(root: Path) -> list[str]:
    """Every tracked path this manifest claims, in sorted order."""
    tracked = _run_git(["ls-files", "-z", *PINNED_ROOTS, *PINNED_FILES], root=root)
    return sorted(part.decode("utf-8") for part in tracked.split(b"\0") if part)


def build_manifest(root: Path) -> dict[str, object]:
    paths = pinned_paths(root)
    return {
        "integration": "speckit-extensions",
        "version": _speckit_version(root),
        "vendored_in": "1eb0c98e6b7dc9033871c9bae46ca080ac39a45c",
        "source": "github/spec-kit",
        "note": (
            "Locally authored. Upstream's installer does not write this file, so it "
            "survives a re-vendor only because scripts/pin_speckit_extensions.py "
            "regenerates it. Hashes are of the git blob, not the working tree."
        ),
        "files": {path: blob_sha256(path, root=root) for path in paths},
    }


def _speckit_version(root: Path) -> str:
    """Reuse the version already pinned by init-options, never a second claim."""
    options = json.loads(
        (root / ".specify/init-options.json").read_text(encoding="utf-8")
    )
    version = options.get("speckit_version")
    if not isinstance(version, str) or not version.strip():
        raise SystemExit("init-options.json has no usable speckit_version")
    return version


def verify(root: Path) -> list[str]:
    """Return every drift finding; empty means the pinned surface is intact."""
    manifest_path = root / MANIFEST
    if not manifest_path.is_file():
        return [f"{MANIFEST.as_posix()}: missing; run with --write"]
    declared = json.loads(manifest_path.read_text(encoding="utf-8"))
    files = declared.get("files")
    if not isinstance(files, dict):
        return [f"{MANIFEST.as_posix()}: 'files' must be an object"]

    problems: list[str] = []
    observed = set(pinned_paths(root))
    claimed = set(files)
    for path in sorted(observed - claimed):
        problems.append(f"{path}: tracked under a pinned root but NOT in the manifest")
    for path in sorted(claimed - observed):
        problems.append(f"{path}: pinned by the manifest but no longer tracked")
    for path in sorted(observed & claimed):
        actual = blob_sha256(path, root=root)
        if actual != files[path]:
            problems.append(
                f"{path}: content drift; expected {files[path]}, observed {actual}"
            )
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="regenerate the manifest in place"
    )
    args = parser.parse_args(argv)

    if args.write:
        manifest = build_manifest(REPO_ROOT)
        (REPO_ROOT / MANIFEST).write_text(
            json.dumps(manifest, indent=2, sort_keys=False) + "\n", encoding="utf-8"
        )
        print(f"[OK] pinned {len(manifest['files'])} files into {MANIFEST.as_posix()}")
        return 0

    problems = verify(REPO_ROOT)
    for problem in problems:
        print(f"[DRIFT] {problem}", file=sys.stderr)
    if problems:
        print(f"{len(problems)} provenance finding(s)", file=sys.stderr)
        return 1
    print(f"[OK] {MANIFEST.as_posix()}: no drift")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
