"""Unit tests for HR2 (declared SCD type per gold dimension)."""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from retail.core import RuleContext, Severity
from retail.rules.scd_policy import check_hr2

pytestmark = pytest.mark.unit

_REPO = Path(__file__).resolve().parents[2]


def _map(tmp_path: Path, table: str, yaml_text: str) -> str:
    """Write a source-map.yaml under tmp_path/mappings/<table>/; return its rel path."""
    rel = f"mappings/{table}/source-map.yaml"
    dest = tmp_path / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(yaml_text, encoding="utf-8")
    return rel


def _mig(tmp_path: Path, table: str, sql: str) -> str:
    """Write a gold migration under tmp_path/warehouse/migrations/; return rel path."""
    rel = f"warehouse/migrations/0001_create_gold_{table}_star.sql"
    dest = tmp_path / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(sql, encoding="utf-8")
    return rel


def _ctx(tmp_path: Path, *rel: str) -> RuleContext:
    return RuleContext(repo_root=tmp_path, tracked_files=tuple(rel))


_DDL_INSERT_DROP_REBUILD = """\
BEGIN;
DROP TABLE IF EXISTS gold.dim_widget;
DROP TABLE IF EXISTS gold.dim_other;

CREATE TABLE gold.dim_other (other_sk INT, other_name TEXT);
INSERT INTO gold.dim_other (other_name) SELECT other_name FROM silver.widgets;

CREATE TABLE gold.dim_widget (
  widget_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  widget_name TEXT
);
INSERT INTO gold.dim_widget (widget_name)
SELECT widget_name FROM silver.widgets;
COMMIT;
"""

_CTAS_DROP_REBUILD = """\
BEGIN;
DROP TABLE IF EXISTS gold.dim_widget;
CREATE TABLE gold.dim_widget AS SELECT widget_name FROM silver.widgets;
COMMIT;
"""


# --- US1: valid declarations pass; invalid value fails closed ---


def test_hr2_valid_declarations_produce_no_finding(tmp_path: Path) -> None:
    yaml_text = (
        "gold_star:\n"
        "  dimensions:\n"
        "    - name: dim_a\n"
        "      scd_type: type_1\n"
        "    - name: dim_b\n"
        "      scd_type: type_2\n"
    )
    rel = _map(tmp_path, "t1", yaml_text)
    ctx = _ctx(tmp_path, rel)
    assert list(check_hr2(ctx)) == []


def test_hr2_invalid_value_fails_closed(tmp_path: Path) -> None:
    yaml_text = (
        "gold_star:\n  dimensions:\n    - name: dim_a\n      scd_type: quarterly\n"
    )
    rel = _map(tmp_path, "t2", yaml_text)
    ctx = _ctx(tmp_path, rel)
    findings = list(check_hr2(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert findings[0].rule_id == "HR2"
    assert "dim_a" in findings[0].message
    assert "quarterly" in findings[0].message


def test_hr2_invalid_value_clears_when_corrected(tmp_path: Path) -> None:
    yaml_text = "gold_star:\n  dimensions:\n    - name: dim_a\n      scd_type: type_1\n"
    rel = _map(tmp_path, "t2b", yaml_text)
    ctx = _ctx(tmp_path, rel)
    assert list(check_hr2(ctx)) == []


# --- US2 (MVP): type_2 + drop-and-rebuild fails closed; type_1 never fires ---


def test_hr2_type2_ddl_insert_drop_rebuild_fails_closed(tmp_path: Path) -> None:
    yaml_text = (
        "gold_star:\n  dimensions:\n    - name: gold.dim_widget\n"
        "      scd_type: type_2\n"
    )
    map_rel = _map(tmp_path, "widgets", yaml_text)
    mig_rel = _mig(tmp_path, "widgets", _DDL_INSERT_DROP_REBUILD)
    ctx = _ctx(tmp_path, map_rel, mig_rel)
    findings = list(check_hr2(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert findings[0].rule_id == "HR2"
    assert (
        "dim_widget" in findings[0].message or "gold.dim_widget" in findings[0].message
    )
    assert findings[0].locator == mig_rel


def test_hr2_type2_ctas_drop_rebuild_fails_closed(tmp_path: Path) -> None:
    yaml_text = (
        "gold_star:\n  dimensions:\n    - name: gold.dim_widget\n"
        "      scd_type: type_2\n"
    )
    map_rel = _map(tmp_path, "widgets_ctas", yaml_text)
    mig_rel = _mig(tmp_path, "widgets_ctas", _CTAS_DROP_REBUILD)
    ctx = _ctx(tmp_path, map_rel, mig_rel)
    findings = list(check_hr2(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR


def test_hr2_type1_drop_rebuild_never_fires(tmp_path: Path) -> None:
    yaml_text = (
        "gold_star:\n  dimensions:\n    - name: gold.dim_widget\n"
        "      scd_type: type_1\n"
    )
    map_rel = _map(tmp_path, "widgets_t1", yaml_text)
    mig_rel = _mig(tmp_path, "widgets_t1", _DDL_INSERT_DROP_REBUILD)
    ctx = _ctx(tmp_path, map_rel, mig_rel)
    assert list(check_hr2(ctx)) == []


def test_hr2_type2_declaration_clears_by_switching_to_type1(tmp_path: Path) -> None:
    """Mutation check: same migration, dimension changed from type_2 to type_1."""
    yaml_text = (
        "gold_star:\n  dimensions:\n    - name: gold.dim_widget\n"
        "      scd_type: type_1\n"
    )
    map_rel = _map(tmp_path, "widgets_mut", yaml_text)
    mig_rel = _mig(tmp_path, "widgets_mut", _DDL_INSERT_DROP_REBUILD)
    ctx = _ctx(tmp_path, map_rel, mig_rel)
    assert list(check_hr2(ctx)) == []


def test_hr2_type2_no_migration_yet_fires_nothing(tmp_path: Path) -> None:
    yaml_text = (
        "gold_star:\n  dimensions:\n    - name: gold.dim_widget\n"
        "      scd_type: type_2\n"
    )
    map_rel = _map(tmp_path, "widgets_nomig", yaml_text)
    ctx = _ctx(tmp_path, map_rel)  # no migration tracked
    assert list(check_hr2(ctx)) == []


def test_hr2_type2_scoped_to_own_table_not_sibling_type1_dim(tmp_path: Path) -> None:
    """A type_1 sibling's drop-and-rebuild in the same file must not false-positive
    against an unrelated type_2 dimension that this migration does not touch."""
    yaml_text = (
        "gold_star:\n"
        "  dimensions:\n"
        "    - name: gold.dim_other\n"
        "      scd_type: type_1\n"
        "    - name: gold.dim_unbuilt\n"
        "      scd_type: type_2\n"
    )
    map_rel = _map(tmp_path, "widgets_scope", yaml_text)
    mig_rel = _mig(tmp_path, "widgets_scope", _DDL_INSERT_DROP_REBUILD)
    ctx = _ctx(tmp_path, map_rel, mig_rel)
    # dim_unbuilt is not in the migration at all -> no finding fabricated
    assert list(check_hr2(ctx)) == []


def test_hr2_ambiguous_migration_set_fails_closed(tmp_path: Path) -> None:
    yaml_text = (
        "gold_star:\n  dimensions:\n    - name: gold.dim_widget\n"
        "      scd_type: type_2\n"
    )
    map_rel = _map(tmp_path, "widgets_dup", yaml_text)
    mig1 = _mig(tmp_path, "widgets_dup", _DDL_INSERT_DROP_REBUILD)
    # a second, differently-prefixed file matching the same glob
    mig2_rel = "warehouse/migrations/0002_create_gold_widgets_dup_star.sql"
    (tmp_path / mig2_rel).write_text(_CTAS_DROP_REBUILD, encoding="utf-8")
    ctx = _ctx(tmp_path, map_rel, mig1, mig2_rel)
    findings = list(check_hr2(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert "widgets_dup" in findings[0].message


# --- US3: undeclared scd_type is a Needs-decision, never a silent default ---


def test_hr2_missing_key_is_needs_decision(tmp_path: Path) -> None:
    # scd_enforced: true opts the map into adoption, so a missing declaration is
    # the Needs-decision ERROR (an un-adopted map would be grandfathered).
    yaml_text = "gold_star:\n  scd_enforced: true\n  dimensions:\n    - name: dim_a\n"
    rel = _map(tmp_path, "t3", yaml_text)
    ctx = _ctx(tmp_path, rel)
    findings = list(check_hr2(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert "dim_a" in findings[0].message
    assert findings[0].locator == f"{rel}:dim_a"


def test_hr2_missing_key_is_grandfathered_on_unadopted_map(tmp_path: Path) -> None:
    """Owner ruling 2026-07-05: a map declaring scd_type on NO dimension and not
    opting in is grandfathered -- HR2 fires no missing-declaration ERROR."""
    yaml_text = "gold_star:\n  dimensions:\n    - name: dim_a\n    - name: dim_b\n"
    rel = _map(tmp_path, "t3_grandfathered", yaml_text)
    ctx = _ctx(tmp_path, rel)
    assert list(check_hr2(ctx)) == []


@pytest.mark.parametrize("placeholder", ['""', "null", "TBD", "tbd"])
def test_hr2_placeholder_values_are_needs_decision_not_invalid(
    tmp_path: Path, placeholder: str
) -> None:
    yaml_text = (
        "gold_star:\n  scd_enforced: true\n  dimensions:\n"
        f"    - name: dim_a\n      scd_type: {placeholder}\n"
    )
    safe_name = placeholder.strip('"').lower()
    rel = _map(tmp_path, f"t3b_{safe_name}", yaml_text)
    ctx = _ctx(tmp_path, rel)
    findings = list(check_hr2(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    # Needs-decision message, not an "invalid value" message
    assert "declare" in findings[0].message.lower()


def test_hr2_two_undeclared_dimensions_produce_two_findings(tmp_path: Path) -> None:
    # adopting map (scd_enforced) with two undeclared dims -> two ERRORs
    yaml_text = (
        "gold_star:\n  scd_enforced: true\n  dimensions:\n"
        "    - name: dim_a\n    - name: dim_b\n"
    )
    rel = _map(tmp_path, "t4", yaml_text)
    ctx = _ctx(tmp_path, rel)
    findings = list(check_hr2(ctx))
    assert len(findings) == 2
    names = {f.locator for f in findings}
    assert names == {f"{rel}:dim_a", f"{rel}:dim_b"}


def test_hr2_undeclared_clears_when_one_dimension_is_declared(tmp_path: Path) -> None:
    yaml_text = (
        "gold_star:\n"
        "  dimensions:\n"
        "    - name: dim_a\n"
        "      scd_type: type_1\n"
        "    - name: dim_b\n"
    )
    rel = _map(tmp_path, "t5", yaml_text)
    ctx = _ctx(tmp_path, rel)
    findings = list(check_hr2(ctx))
    assert len(findings) == 1
    assert findings[0].locator == f"{rel}:dim_b"


# --- out-of-scope entities never read ---


def test_hr2_never_reads_degenerate_dimensions_or_date_dimension(
    tmp_path: Path,
) -> None:
    yaml_text = (
        "gold_star:\n"
        "  dimensions:\n"
        "    - name: dim_a\n"
        "      scd_type: type_1\n"
        "  degenerate_dimensions:\n"
        "    - transaction_id\n"
        "  date_dimension:\n"
        "    name: dim_date\n"
        "    method: generate_series\n"
    )
    rel = _map(tmp_path, "t6", yaml_text)
    ctx = _ctx(tmp_path, rel)
    assert list(check_hr2(ctx)) == []


# --- landing rule: both real committed maps are GRANDFATHERED (owner ruling
# 2026-07-05) -- they declare scd_type on no dimension and do not opt in, so HR2
# is <no-finding> on the committed tree while enforcing on every new/touched map ---


def test_hr2_grandfathers_the_real_committed_maps() -> None:
    """Both committed maps predate this feature and declare no scd_type on any
    gold_star.dimensions[] entry and do not set scd_enforced, so the grandfather
    ruling (2026-07-05) exempts them: HR2 emits NOTHING on the committed tree.
    Pins that HR2 lands <no-finding> (a future regression that made it fire
    retroactively on an already-approved map would be caught here)."""
    rels = [
        "mappings/retail_store_sales/source-map.yaml",
        "mappings/demo_sample_orders/source-map.yaml",
    ]
    tracked = tuple(rel for rel in rels if (_REPO / rel).exists())
    assert tracked, "expected fixture maps are missing from the repo"
    ctx = RuleContext(repo_root=_REPO, tracked_files=tracked)
    assert list(check_hr2(ctx)) == []


# --- polish: static-only, no numeric score, no write ---


def test_hr2_module_imports_no_database_driver() -> None:
    src = (_REPO / "src" / "retail" / "rules" / "scd_policy.py").read_text(
        encoding="utf-8"
    )
    for forbidden in ("import psycopg", "import sqlalchemy", ".connect(", "DSN"):
        assert forbidden not in src


def test_hr2_module_never_writes_a_map_or_migration_file() -> None:
    src = (_REPO / "src" / "retail" / "rules" / "scd_policy.py").read_text(
        encoding="utf-8"
    )
    for forbidden in ('mode="w"', "mode='w'", "write_text(", "write_bytes("):
        assert forbidden not in src


def test_hr2_messages_have_no_numeric_score(tmp_path: Path) -> None:
    yaml_text = "gold_star:\n  scd_enforced: true\n  dimensions:\n    - name: dim_a\n"
    rel = _map(tmp_path, "t7", yaml_text)
    ctx = _ctx(tmp_path, rel)
    for f in check_hr2(ctx):
        assert "%" not in f.message


def test_hr2_ambiguous_migration_message_has_no_numeric_tally(tmp_path: Path) -> None:
    """FR-013: no message may report a raw finding/file count (hard rule #9),
    including the ambiguous-migration-set branch (a candidate leak point since
    it must name multiple files)."""
    yaml_text = (
        "gold_star:\n  dimensions:\n    - name: gold.dim_widget\n"
        "      scd_type: type_2\n"
    )
    map_rel = _map(tmp_path, "widgets_tally", yaml_text)
    mig1 = _mig(tmp_path, "widgets_tally", _DDL_INSERT_DROP_REBUILD)
    mig2_rel = "warehouse/migrations/0002_create_gold_widgets_tally_star.sql"
    (tmp_path / mig2_rel).write_text(_CTAS_DROP_REBUILD, encoding="utf-8")
    ctx = _ctx(tmp_path, map_rel, mig1, mig2_rel)
    findings = list(check_hr2(ctx))
    assert len(findings) == 1
    assert not re.search(r"\b\d+\s+files?\b", findings[0].message)
