"""Regression tests for issue #497 (the dbt scaffolder built a divergent calendar).

`dbt/scaffold/model_plan.py` hardcoded

    _DATE_COLUMNS = ("full_date", "year", "quarter", "month", "day", "iso_week")

and `_date_dimension` built `(surrogate, *_DATE_COLUMNS)` while NEVER reading
`attributes` -- unlike `_dimension_model`, which reads them for every explicit
dimension. So every scaffolded date dimension got those six columns regardless of
the approved map, and it disagreed with `warehouse/migrations/0004_*.sql`
(gold.dim_date_rss), which carries `month_name`, `day_name` and `is_weekend` too.
The same approved map therefore produced a STRUCTURALLY DIFFERENT date dimension
on the two build paths, and nothing detected it: the parity audit compares values
only (that is #492) and a calendar's member count matches whether or not
`month_name` exists.

Resolution (owner-ruled R6, as amended): ONE SHARED RESOLVER,
`star_discovery.resolve_date_attributes`, consumed by BOTH the builder
(`dbt/scaffold/model_plan`) and the reader (`gap_detector`). `_DATE_COLUMNS` is
DELETED rather than corrected -- a second hardcoded tuple IS the defect #497
reports, so neither consumer may keep a private list. The deduplication is the part
that actually closes the issue.

DEFAULT WHEN `attributes` IS ABSENT: the full RC15 calendar, which equals the
migrations DDL set. Since ZERO tracked maps declare `date_dimension.attributes`,
that default governs EVERY existing map: any other default would relocate the
divergence instead of removing it.

The prior #491 ruling STANDS and is not overturned. It forbade honoring
`date_dimension.attributes` in ONE consumer, because a lone reader honoring it
while the builder ignored it manufactures a fresh cross-surface disagreement (the
#487 defect). Honoring it in the SHARED resolver is the opposite move: it keeps the
two surfaces in lockstep, so a narrowed calendar narrows both. RC15 remains the
authority for what a calendar CONTAINS; `attributes` selects from it and can never
introduce a column (a calendar is generated by generate_series, so an off-contract
attribute has no source column to derive from and is rejected).

`tests/unit/test_issue_regression_491.py` passes UNMODIFIED under this change --
its ruling docstring needed no edit.

NOT covered here: asserting the two build paths' column sets match inside the
parity audit. That is #492, deliberately scoped to value-only by ratified
ADR-0009.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from seshat.dbt.contracts import FactBinding
from seshat.dbt.scaffold import model_plan

pytestmark = pytest.mark.unit

# The shared ordered declaration is imported LAZILY, inside the tests that assert
# it specifically. Importing it at module scope would turn every behavioral test in
# this file into a collection ERROR on a tree without the fix, which proves only
# that a new constant is missing -- not that the calendar the scaffolder BUILDS was
# wrong. Each behavioral test below must fail on its own assertion instead.

_REPO = Path(__file__).resolve().parents[2]
TABLE_ID = "orders"

_FACT = FactBinding(
    name="fct_orders",
    business_key=("order_id",),
    additive_money_measures=("net_sales",),
)


def _map(date_dimension: dict | None) -> dict:
    return {
        "meta": {"table_id": TABLE_ID, "grain": "one row = one order line"},
        "columns": [
            {
                "source_name": "order_id",
                "decision": "keep",
                "rename_to": "order_id",
                "silver_type": "text",
            },
            {
                "source_name": "net_sales",
                "decision": "keep",
                "rename_to": "net_sales",
                "silver_type": "numeric(12,2)",
            },
            {
                "source_name": "customer_id",
                "decision": "keep",
                "rename_to": "customer_id",
                "silver_type": "text",
            },
            {
                "source_name": "order_date",
                "decision": "keep",
                "rename_to": "order_date",
                "silver_type": "date",
            },
        ],
        "gold_star": {
            "fact": {
                "name": "gold.fct_orders",
                "grain": "one row = one order line",
                "business_key": "order_id",
                "measures": ["net_sales"],
                "additive_money_measures": ["net_sales"],
            },
            "dimensions": [
                {
                    "name": "gold.dim_customer",
                    "surrogate_key": "customer_sk",
                    "attributes": ["customer_id"],
                }
            ],
            "date_dimension": date_dimension,
        },
    }


def _plan(date_dimension: dict | None) -> model_plan.ScaffoldPlan:
    source = model_plan.MapSource(
        document=_map(date_dimension),
        source_map=f"mappings/{TABLE_ID}/source-map.yaml",
        source_map_revision="0" * 40,
    )
    return model_plan.build_scaffold_plan(source, TABLE_ID, _FACT)


def _date_model(date_dimension: dict | None) -> model_plan.ModelSpec:
    plan = _plan(date_dimension)
    (model,) = [d for d in plan.dimensions if d.name == "dim_date"]
    return model


_DEFAULTED = {"name": "gold.dim_date", "surrogate_key": "date_sk"}


def _migration_ddl_columns() -> list[str]:
    """The reference star's date-dimension columns, read from the committed DDL."""
    ddl = next(_REPO.glob("warehouse/migrations/0004_*.sql")).read_text(
        encoding="utf-8"
    )
    block = re.search(
        r"create table\s+gold\.dim_date_rss\s*\((.*?)\);",
        ddl,
        re.IGNORECASE | re.DOTALL,
    )
    assert block, "could not locate the reference date-dimension DDL"
    return [
        m.group(1)
        for line in block.group(1).splitlines()
        if (m := re.match(r"\s*([a-z_][a-z0-9_]*)\s+[A-Za-z]", line))
    ]


# ---------------------------------------------------------------------------
# The default IS the fix: it must equal the migrations DDL set
# ---------------------------------------------------------------------------


def test_the_absent_case_default_equals_the_migrations_ddl_set() -> None:
    """THE regression. Zero tracked maps declare `attributes`, so this default
    governs every existing map. Pre-fix it was 7 columns; the DDL has 10."""
    built = [c.name for c in _date_model(_DEFAULTED).columns]

    assert built == _migration_ddl_columns(), (
        "the scaffolded date dimension diverges from the migrations star: "
        f"scaffolded={built} ddl={_migration_ddl_columns()}"
    )


@pytest.mark.parametrize("attr", ["month_name", "day_name", "is_weekend"])
def test_the_columns_the_scaffolder_used_to_omit_are_built(attr: str) -> None:
    """These three are exactly what `_DATE_COLUMNS` dropped versus the DDL."""
    built = {c.name for c in _date_model(_DEFAULTED).columns}

    assert attr in built, f"{attr!r} is in the migrations star but was not scaffolded"


def test_the_default_is_the_shared_declaration_not_a_local_copy() -> None:
    """#497 is a two-declarations bug; a second local tuple would recreate it."""
    from seshat.star_discovery import RC15_CALENDAR_COLUMNS

    built = [c.name for c in _date_model(_DEFAULTED).columns]

    assert built == ["date_sk", *RC15_CALENDAR_COLUMNS]
    assert not hasattr(model_plan, "_DATE_COLUMNS"), (
        "a module-local date column list reintroduces the divergent second "
        "declaration issue #497 removed"
    )


def test_the_ordered_declaration_and_the_set_cannot_disagree() -> None:
    """`RC15_CALENDAR_ATTRIBUTES` (readers, #491) is derived from the ordered
    tuple (builders, #497), so one edit updates both."""
    from seshat.star_discovery import (
        RC15_CALENDAR_ATTRIBUTES,
        RC15_CALENDAR_COLUMNS,
    )

    assert frozenset(RC15_CALENDAR_COLUMNS) == RC15_CALENDAR_ATTRIBUTES
    assert len(RC15_CALENDAR_COLUMNS) == len(set(RC15_CALENDAR_COLUMNS))


# ---------------------------------------------------------------------------
# `attributes` is now READ, like every other dimension's
# ---------------------------------------------------------------------------


def test_declared_attributes_are_honored() -> None:
    """The reported defect: the map said one thing, the scaffolder built another."""
    model = _date_model({**_DEFAULTED, "attributes": ["full_date", "year", "month"]})

    assert [c.name for c in model.columns] == ["date_sk", "full_date", "year", "month"]


def test_declared_attributes_keep_the_declared_order() -> None:
    model = _date_model({**_DEFAULTED, "attributes": ["year", "full_date"]})

    assert [c.name for c in model.columns] == ["date_sk", "year", "full_date"]


def test_an_empty_attributes_list_falls_back_to_the_documented_default() -> None:
    model = _date_model({**_DEFAULTED, "attributes": []})

    assert [c.name for c in model.columns] == ["date_sk", *_migration_ddl_columns()[1:]]


# ---------------------------------------------------------------------------
# Calendar columns stay GENERATED -- never cited to bronze
# ---------------------------------------------------------------------------


def test_every_calendar_column_is_date_spine_derived_with_no_source_citation() -> None:
    """A calendar is generated by generate_series over the approved span, so no
    `gold_placement` can point at it (#491). Declared attributes are no different:
    citing them to bronze would fabricate provenance."""
    model = _date_model({**_DEFAULTED, "attributes": ["full_date", "year"]})

    for column in model.columns:
        assert column.derivation == "date_spine", column.name
        assert column.source_columns == (), column.name


def test_the_surrogate_stays_first_so_the_date_renderer_is_dispatched() -> None:
    """`orchestrator._dimension_sql` selects the RC15 calendar renderer on
    `columns[0].derivation`; a reordering would silently emit the entity-dimension
    SQL (select ... from stg_*) for a calendar."""
    from seshat.dbt.scaffold import orchestrator

    date_dimension = {**_DEFAULTED, "attributes": ["full_date"]}
    plan = _plan(date_dimension)
    model = _date_model(date_dimension)

    assert model.columns[0].name == "date_sk"
    assert "generate_series" in orchestrator._dimension_sql(model, plan)


# ---------------------------------------------------------------------------
# Off-contract attributes fail CLOSED (no fresh cross-surface disagreement)
# ---------------------------------------------------------------------------


def test_an_attribute_outside_the_rc15_calendar_is_rejected() -> None:
    """Accepting `fiscal_year` would build a column the `RC15_CALENDAR_ATTRIBUTES`
    readers do not know about -- reintroducing the cross-surface disagreement #497
    exists to remove. RC15 is the authority; `attributes` selects from it."""
    with pytest.raises(model_plan.ScaffoldError, match="fiscal_year"):
        _date_model({**_DEFAULTED, "attributes": ["full_date", "fiscal_year"]})


def test_a_non_identifier_attribute_is_still_rejected() -> None:
    """Rejected as OFF-CONTRACT (it is not an RC15 name), which subsumes the
    identifier check -- the resolver only ever yields RC15 names, so a malformed
    one cannot reach the builder."""
    with pytest.raises(model_plan.ScaffoldError, match="Full Date"):
        _date_model({**_DEFAULTED, "attributes": ["Full Date"]})


# ---------------------------------------------------------------------------
# Business key: a calendar keys on full_date, never blindly attributes[0]
# ---------------------------------------------------------------------------


def test_the_business_key_is_full_date_even_when_declared_second() -> None:
    """`_dimension_model` uses `attributes[0]`; for a calendar that would key
    `[year, full_date]` on `year`, which is not unique per row."""
    model = _date_model({**_DEFAULTED, "attributes": ["year", "full_date"]})

    assert model.business_key == ("full_date",)


def test_the_default_business_key_is_unchanged() -> None:
    """The committed reference contract says `business_key: [full_date]`."""
    assert _date_model(_DEFAULTED).business_key == ("full_date",)


def test_a_calendar_without_full_date_keys_on_its_surrogate_not_an_attribute() -> None:
    """Codex review P2 (third finding). Falling back to `attributes[0]` the way
    `_dimension_model` does keyed a DAILY calendar on `year` -- hundreds of rows share
    it, so the generated `meta.seshat.business_key` misstated the grain AND
    `yaml_render` emitted a `unique` test that would fail at run. The surrogate is
    the per-day smart key, so it is always unique at the declared grain."""
    model = _date_model({**_DEFAULTED, "attributes": ["year", "month"]})

    assert model.business_key == ("date_sk",)


@pytest.mark.parametrize(
    "attributes",
    [
        None,
        ["full_date"],
        ["full_date", "year"],
        ["year", "full_date"],
        ["year", "month"],
    ],
    ids=["defaulted", "minimal", "narrowed", "reordered", "no-full-date"],
)
def test_the_business_key_is_always_unique_per_calendar_day(
    attributes: list[str] | None,
) -> None:
    """The grain sentence promises one row per calendar date, and `yaml_render` emits
    `unique`/`not_null` on the business key -- so the key must be a per-DAY column in
    every narrowing. `full_date` and `date_sk` are the only two that qualify."""
    date_dimension = dict(_DEFAULTED)
    if attributes is not None:
        date_dimension["attributes"] = attributes
    model = _date_model(date_dimension)

    (key,) = model.business_key
    assert key in {"full_date", "date_sk"}, (
        f"business_key {key!r} is not unique per calendar day, but the grain is "
        f"{model.grain!r}"
    )
    assert key in {c.name for c in model.columns}, (
        f"business_key {key!r} is not among the model's columns"
    )


# ---------------------------------------------------------------------------
# Pre-existing behavior must not regress
# ---------------------------------------------------------------------------


def test_a_map_without_a_date_dimension_still_builds_no_calendar() -> None:
    plan = _plan(None)

    assert [d.name for d in plan.dimensions] == ["dim_customer"]


def test_the_grain_sentence_is_unchanged() -> None:
    assert (
        _date_model(_DEFAULTED).grain
        == "one row per calendar date in the approved span"
    )


def test_entity_dimensions_still_cite_bronze() -> None:
    """The fix must not leak date-spine semantics into explicit dimensions."""
    plan = _plan(_DEFAULTED)
    (customer,) = [d for d in plan.dimensions if d.name == "dim_customer"]

    attribute = customer.columns[1]
    assert attribute.name == "customer_id"
    assert attribute.source_columns == ("bronze.orders.customer_id",)


# ---------------------------------------------------------------------------
# The repo's own reference star: all build surfaces agree
# ---------------------------------------------------------------------------


def test_the_reference_star_agrees_across_every_build_surface() -> None:
    """The scaffolder, the committed dbt contract, the committed completed SQL and
    the migrations DDL must all describe the SAME calendar. Pre-fix the scaffolder
    was the lone outlier at 7 columns."""
    import yaml

    from seshat.dbt.scaffold import orchestrator

    plan = orchestrator._build_plan(_REPO, "retail_store_sales")
    scaffolded = [
        c.name for d in plan.dimensions if d.name == "dim_date_rss" for c in d.columns
    ]

    document = yaml.safe_load(
        (_REPO / "dbt/models/marts/retail_store_sales/_models.yml").read_text(
            encoding="utf-8"
        )
    )
    contract = [
        c["name"]
        for m in document["models"]
        if m["name"] == "dim_date_rss"
        for c in m["columns"]
    ]

    assert scaffolded == contract, (
        "the scaffolder and the committed dbt column contract disagree: "
        f"scaffolded={scaffolded} contract={contract}"
    )
    assert scaffolded == _migration_ddl_columns()


# ---------------------------------------------------------------------------
# THE core guard: both consumers resolve the SAME set from the SAME input
# ---------------------------------------------------------------------------
#
# This is the regression guard for the amended ruling. #497 is a
# two-declarations bug, so the invariant is not "the builder is right" but "the
# builder and the reader cannot disagree". `gap_detector` decides which columns a
# star makes AVAILABLE (and can false-block an APPROVED metric contract -- #491);
# `model_plan` decides which columns get BUILT. If those drift, the tool reports a
# column present that no build path produces.


def _reader_calendar_columns(date_dimension: dict) -> set[str]:
    """The calendar attributes `gap_detector` believes the star exposes.

    Isolated by DIFFERENCE against the same star with no date dimension, so only
    tokens the date path contributes are compared -- never the fact's measures or an
    entity dim's attributes, which `_collect_gold` also harvests.
    """
    from seshat.gap_detector import _collect_gold

    def tokens(date_dim: dict | None) -> set[str]:
        star: dict = {
            "fact": {"name": "gold.fct_orders", "measures": ["net_sales"]},
            "dimensions": [],
        }
        if date_dim is not None:
            star["date_dimension"] = date_dim
        _, cols = _collect_gold({"gold_star": star})
        return cols

    contributed = tokens(date_dimension) - tokens(None)
    return contributed - {date_dimension.get("surrogate_key")}


def _builder_calendar_columns(date_dimension: dict) -> set[str]:
    """The calendar attributes the dbt scaffolder actually BUILDS."""
    surrogate = date_dimension.get("surrogate_key")
    return {c.name for c in _date_model(date_dimension).columns if c.name != surrogate}


@pytest.mark.parametrize(
    "attributes",
    [
        None,  # the absent-case default -- governs every tracked map
        ["full_date", "year"],  # a NARROWED calendar
        ["full_date"],  # the narrowest useful calendar
        ["year", "full_date"],  # declared out of DDL order
    ],
    ids=["defaulted", "narrowed", "minimal", "reordered"],
)
def test_the_builder_and_the_reader_resolve_the_same_calendar(
    attributes: list[str] | None,
) -> None:
    """Cross-surface agreement. Pre-fix the builder used a private 6-entry
    `_DATE_COLUMNS` while the reader used the 9-entry RC15 set, so they disagreed
    even in the DEFAULT case; and honoring `attributes` in only one of them would
    have made every narrowed calendar disagree too."""
    date_dimension = dict(_DEFAULTED)
    if attributes is not None:
        date_dimension["attributes"] = attributes

    builder = _builder_calendar_columns(date_dimension)
    reader = _reader_calendar_columns(date_dimension)

    assert builder == reader, (
        "the dbt builder and the gap_detector reader disagree about the calendar: "
        f"built-but-not-reported={sorted(builder - reader)} "
        f"reported-but-not-built={sorted(reader - builder)}"
    )


def test_the_reader_never_claims_a_column_the_builder_does_not_build() -> None:
    """The dangerous direction, stated on its own: a column reported AVAILABLE that
    no build path produces lets a metric contract bind to something that will not
    exist in the warehouse."""
    date_dimension = {**_DEFAULTED, "attributes": ["full_date", "year"]}

    phantom = _reader_calendar_columns(date_dimension) - _builder_calendar_columns(
        date_dimension
    )

    assert phantom == set(), f"reported available but never built: {sorted(phantom)}"


def test_neither_consumer_keeps_a_private_calendar_list() -> None:
    """The deduplication IS the fix. Both modules must route through the shared
    resolver, and neither may REDEFINE the calendar set.

    Checked by module attribute, not by source string: asserting a name like
    `iso_week` is absent from the source would break the moment any docstring in
    either module explains the calendar (this repo has hit that docstring-prose
    duplication trap before), and a comment naming a column is not a second
    declaration.
    """
    import inspect

    from seshat import gap_detector, star_discovery

    # The old private tuple is gone, and no equivalent is re-exported.
    assert not hasattr(model_plan, "_DATE_COLUMNS")
    for module in (model_plan, gap_detector):
        source = inspect.getsource(module)
        assert "resolve_date_attributes" in source, (
            f"{module.__name__} does not consume the shared resolver"
        )
        # No consumer may bind its own copy of the calendar set under ANY name: a
        # module-level collection of calendar names is the defect coming back.
        for name, value in vars(module).items():
            if isinstance(value, (tuple, frozenset, set, list)) and value:
                overlap = {v for v in value if isinstance(v, str)} & set(
                    star_discovery.RC15_CALENDAR_COLUMNS
                )
                assert not overlap, (
                    f"{module.__name__}.{name} holds calendar column names "
                    f"{sorted(overlap)}; the set belongs to star_discovery alone"
                )

    # star_discovery is the single declaration site.
    assert star_discovery.RC15_CALENDAR_COLUMNS


# ---------------------------------------------------------------------------
# Narrowing vs an APPROVED metric contract (the severe half of #491)
# ---------------------------------------------------------------------------


def test_a_narrowed_calendar_blocks_a_contract_binding_an_excluded_column() -> None:
    """Ruled: this SHOULD block, and it is not a #491 regression.

    #491's defect was the reader reporting a column absent that the star DID build
    -- the tool contradicting a recorded human approval about a column that exists.
    Here the map has deliberately declared a NARROWER calendar, so `month_name`
    genuinely will not exist in the warehouse. Reporting it missing is the check
    working (fail CLOSED); reporting it available would let an approved contract
    bind to a column no build path produces, which is the failure mode #497 is
    about.

    Reachability: OPT-IN only. No tracked map declares `attributes`, so no existing
    contract changes verdict -- verified by census.
    """
    from seshat.gap_detector import _missing_bound_columns

    narrowed = {**_DEFAULTED, "attributes": ["full_date", "year"]}
    cols = _reader_calendar_columns(narrowed) | {"date_sk"}

    assert _missing_bound_columns({"columns": ["month_name"]}, {"gold_cols": cols}) == [
        "month_name"
    ]
    # A column the narrowed calendar DOES build stays bindable.
    assert _missing_bound_columns({"columns": ["year"]}, {"gold_cols": cols}) == []


def test_the_default_calendar_still_satisfies_a_contract_binding_any_rc15_column() -> (
    None
):
    """The #491 guarantee must survive for every map that does NOT narrow -- which
    is every tracked map today. An approved contract binding `month_name` passes."""
    from seshat.gap_detector import _missing_bound_columns
    from seshat.star_discovery import RC15_CALENDAR_COLUMNS

    cols = _reader_calendar_columns(_DEFAULTED) | {"date_sk"}
    contract = {"columns": list(RC15_CALENDAR_COLUMNS)}

    assert _missing_bound_columns(contract, {"gold_cols": cols}) == []


def test_the_resolver_returns_nothing_for_a_non_mapping() -> None:
    """Documents the contract at the shared boundary: a malformed `date_dimension`
    contributes no calendar rather than raising into either consumer."""
    from seshat.star_discovery import resolve_date_attributes

    assert resolve_date_attributes("not-a-mapping") == ()
    assert resolve_date_attributes(None) == ()


def test_an_advisory_reader_tolerates_an_off_contract_calendar() -> None:
    """`gap_detector` reports gaps; it is not the gate. A malformed map must not
    raise there -- it contributes no attributes, so a bound column stays reported
    MISSING (fail closed) and the loud error belongs to `seshat dbt scaffold`."""
    reported = _reader_calendar_columns(
        {**_DEFAULTED, "attributes": ["full_date", "fiscal_year"]}
    )

    assert reported == set()


# ---------------------------------------------------------------------------
# THE THIRD CONSUMER: conformed-dimension reuse (Codex bot P2 on PR #502)
# ---------------------------------------------------------------------------
#
# `_require_attributes_covered` reconciles a REUSED dim against its OWNER. It read
# both sides' `attributes` RAW via `_dim_attributes`, so a DEFAULTED calendar looked
# like it carried ZERO attributes. Same defect class as #497 itself: a third
# consumer resolving date attributes from the raw declaration instead of the shared
# resolver. Both directions below were reproduced against the pre-fix tree.

_CONFORMED_DATE = {
    "dimensions": {
        "dim_date": {"status": "conformed", "stars": ["owner_star", TABLE_ID]}
    }
}


def _date_dim(attributes: list[str] | None) -> dict:
    dim = {"name": "gold.dim_date", "surrogate_key": "date_sk"}
    if attributes is not None:
        dim["attributes"] = attributes
    return dim


def _owner_star_view(dim: dict, *, as_date_dim: bool = True) -> dict[str, dict]:
    """A committed owner-view for `owner_star`, built the way the orchestrator builds
    it -- via `star_dimension_view`, so the owner's date-slot classification travels
    INSIDE the view and cannot be omitted (issue #497)."""
    from seshat.star_discovery import star_dimension_view

    star: dict = {"fact": {"name": "gold.fct_owner"}}
    if as_date_dim:
        star["dimensions"] = []
        star["date_dimension"] = dim
    else:
        star["dimensions"] = [dim]
    return {"owner_star": star_dimension_view({"gold_star": star})}


def _reuse_plan(
    owner_attrs: list[str] | None,
    reuser_attrs: list[str] | None,
    *,
    owner_as_date_dim: bool = True,
):
    """Build the REUSER's plan, reconciling its date dim against the owner star."""
    source = model_plan.MapSource(
        document=_map(_date_dim(reuser_attrs)),
        source_map=f"mappings/{TABLE_ID}/source-map.yaml",
        source_map_revision="0" * 40,
        conformed_map=_CONFORMED_DATE,
        owner_view=_owner_star_view(
            _date_dim(owner_attrs), as_date_dim=owner_as_date_dim
        ),
    )
    return model_plan.build_scaffold_plan(source, TABLE_ID, _FACT)


def test_default_full_owner_accepts_a_narrowed_reuser() -> None:
    """Direction 1 -- must NOT be wrongly rejected.

    The owner declares no `attributes`, so it builds the FULL RC15 calendar. A
    reuser narrowing to a subset is therefore fully covered. Pre-fix the owner's
    absent key read as zero attributes and this was REJECTED with "owner does not
    carry full_date, year" -- about an owner that does build them.
    """
    plan = _reuse_plan(owner_attrs=None, reuser_attrs=["full_date", "year"])

    assert "dim_date" in plan.reused_dimensions
    assert plan.reused_dimension_owners["dim_date"] == "owner_star"


def test_narrowed_owner_rejects_a_default_full_reuser() -> None:
    """Direction 2 -- must NOT wrongly pass.

    The owner narrowed to `[full_date]`; the reuser declares nothing, so its
    resolver (and its `gap_detector`) says the calendar has all nine columns. Reusing
    the owner's model would silently drop eight of them. Pre-fix this PASSED, because
    the reuser's absent key read as zero attributes -- nothing to be missing.
    """
    from seshat.star_discovery import RC15_CALENDAR_COLUMNS

    with pytest.raises(model_plan.ScaffoldError) as excinfo:
        _reuse_plan(owner_attrs=["full_date"], reuser_attrs=None)

    message = str(excinfo.value)
    reported = message.split("attribute(s) ")[1].split(" on conformed")[0]
    # Exactly the columns the owner narrowed away -- `full_date` IS carried, so it
    # must not be named.
    assert set(reported.split(", ")) == set(RC15_CALENDAR_COLUMNS) - {"full_date"}


def test_identical_default_calendars_reconcile_cleanly() -> None:
    """The common case: neither star narrows, so the resolved sets are equal and
    reuse is permitted. This is every tracked map today (census: 0 narrow)."""
    plan = _reuse_plan(owner_attrs=None, reuser_attrs=None)

    assert "dim_date" in plan.reused_dimensions


def test_a_mixed_classification_is_refused() -> None:
    """Codex review P2 (second finding). The reuser declares `dim_date` as its
    `date_dimension` while the OWNER exposes the same conformed name through
    `dimensions[]`.

    Applying the reuser's calendar classification to the owner expanded a bare ENTITY
    dim to the full RC15 set -- columns `_dimension_model` never builds (it emits the
    surrogate key alone). Reconciliation then PASSED, dropped the reuser's calendar
    model, and left nine columns referenced on an owner model that emits one. Refuse
    instead: neither side's classification may be imposed on the other.
    """
    with pytest.raises(model_plan.ScaffoldError) as excinfo:
        _reuse_plan(owner_attrs=None, reuser_attrs=None, owner_as_date_dim=False)

    message = str(excinfo.value)
    assert "date_dimension" in message and "dimensions[]" in message
    assert "distinct" in message


def test_the_owner_classification_cannot_be_omitted_by_a_caller() -> None:
    """The owner's date-slot classification travels INSIDE `owner_view`, so an
    orchestrator-shaped view always carries it.

    An earlier attempt passed it as a separate optional argument; any caller that
    omitted it silently degraded the owner to an entity dim, reintroducing the same
    asymmetry one layer down (it false-refused the both-sides-default case).
    """
    from seshat.star_discovery import DATE_SLOT_KEY, date_slot_of

    view = _owner_star_view(_date_dim(None))["owner_star"]

    assert DATE_SLOT_KEY in view
    assert date_slot_of(view) == "dim_date"
    # An explicit entity dim of the same name owns the slot instead -> not a date dim.
    entity = _owner_star_view(_date_dim(None), as_date_dim=False)["owner_star"]
    assert date_slot_of(entity) is None


def test_entity_dimension_reuse_still_compares_declared_attributes() -> None:
    """Only the DATE path resolves a default. An entity dim carries exactly what it
    declares, so a reuser attribute the owner lacks must still fail closed."""
    conformed = {
        "dimensions": {
            "dim_customer": {"status": "conformed", "stars": ["owner_star", TABLE_ID]}
        }
    }
    document = _map(_DEFAULTED)
    document["gold_star"]["dimensions"] = [
        {
            "name": "gold.dim_customer",
            "surrogate_key": "customer_sk",
            "attributes": ["customer_id"],
        }
    ]
    source = model_plan.MapSource(
        document=document,
        source_map=f"mappings/{TABLE_ID}/source-map.yaml",
        source_map_revision="0" * 40,
        conformed_map=conformed,
        owner_view={
            "owner_star": {
                "dim_customer": {
                    "name": "gold.dim_customer",
                    "surrogate_key": "customer_sk",
                    "attributes": [],
                }
            }
        },
    )

    with pytest.raises(model_plan.ScaffoldError, match="customer_id"):
        model_plan.build_scaffold_plan(source, TABLE_ID, _FACT)


def test_all_three_consumers_resolve_one_calendar() -> None:
    """Builder, reader, and conformed-reuse reconciler must agree. This is the
    invariant the R6 amendment states; the reuse path was the missing third."""
    from seshat.star_discovery import resolve_date_attributes

    narrowed = {**_DEFAULTED, "attributes": ["full_date", "year"]}
    shared = set(resolve_date_attributes(narrowed))

    assert _builder_calendar_columns(narrowed) == shared
    assert _reader_calendar_columns(narrowed) == shared
    # The reconciler compares the SAME resolved set, so a reuser narrowed exactly
    # like its owner is covered.
    narrowed_both = _reuse_plan(["full_date", "year"], ["full_date", "year"])
    assert "dim_date" in narrowed_both.reused_dimensions
